network_project/main_app/urls.py
from django.urls import path
from . import views

app_name= 'main_app'

urlpatterns = [
    path('forms/', views.get_form, name='forms'),
    path('', views.index, name='index'),
    path('tables/', views.tables, name='tables')
]

network_project/network_project/urls.py
from django.contrib import admin
from django.urls import path, include
from main_app import views

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

network_project/main_app/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length =128)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "student_table"

class Friendship1(models.Model):
    student = models.ForeignKey(Student,related_name="student",on_delete=models.CASCADE)
    friend = models.ForeignKey(Student,related_name="friend",on_delete=models.CASCADE)

    class Meta:
        db_table = "friendship_table"
    

network_project/main_app/forms.py
from django import forms
from .models import Student

class InputForm(forms.Form):
    student = forms.ModelChoiceField(queryset=Student.objects.all().order_by('name'))
    friend1 = forms.ModelChoiceField(queryset=Student.objects.all().order_by('name'))
    friend2 = forms.ModelChoiceField(queryset=Student.objects.all().order_by('name'))
    friend3 = forms.ModelChoiceField(queryset=Student.objects.all().order_by('name'))

network_project/main_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import InputForm
from .generateGraph import create_graph
from .tables import create_table

from .models import Student, Friendship1


# Create your views here.

image_bytes = create_graph()

def index(request):
    context_dict = { 'data' : image_bytes}
    return render(request, 'index.html', context_dict )


def get_form(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = InputForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            data = form.cleaned_data
            student = data['student']
            friend1 = data['friend1']
            friend2 = data['friend2']
            friend3 = data['friend3']

            friendship1 = Friendship1( student = student, friend = friend1)
            friendship1.save()

            friendship2 = Friendship1( student = student, friend = friend2)
            friendship2.save()

            friendship3 = Friendship1( student = student, friend = friend3)
            friendship3.save()

            # ...

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('main_app:index'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = InputForm()

    return render(request, 'forms.html', {'form': form})

def tables(request):
    context_tables = {'tables':create_table()}
    return render(request, 'tables.html',context = context_tables)

network_project/main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <title>Network Analysis</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Network Analysis</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main_app:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main_app:forms' %}">Form <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main_app:tables' %}">Table</a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="container mt-5">
          
          {% block body_block %}
              
          {% endblock body_block %}
              
      </div>
</body>
</html>

network_project/main_app/templates/forms.html
<!DOCTYPE html>
{% extends 'templates/base.html' %}
    
    {% block body_block %}
        <form action="/forms/" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    {% endblock body_block %}

network_project/main_app/templates/index.html
<!DOCTYPE html>
{% extends 'templates/base.html' %}
    
    {% block body_block %}
        {{ data | safe }}
        <h1>Graph</h1>
    {% endblock body_block %}
        

network_project/main_app/templates/main_app/index.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}
    
    {% block body_block %}
        {{ data | safe }}
        <h1>Graph</h1>
    {% endblock body_block %}
        

network_project/main_app/templates/tables.html
<!DOCTYPE html>
{% extends 'templates/base.html' %}
    
    {% block body_block %}
    <table class="table">
        <thead class="th-dark">
            <tr>
                <th scope="col">Student ID</th>
                <th scope="col">Student Name</th>
                <th scope="col">Friend 1</th>
                <th scope="col">Friend 2</th>
                <th scope="col">Friend 3</th>
                <th scope="col">Total Friends</th>
            </tr>
        </thead>
        <tbody>
            {% for k,v in tables.items %}
                <tr>
                    <td scope="row">
                        {{ k }}
                    </td>
                    <td>
                        {{ v.0 }}
                    </td>
                    <td>
                        {{ v.1 }}
                    </td>
                    <td>
                        {{ v.2 }}
                    </td>
                    <td>
                        {{ v.3 }}
                    </td>
                    <td>
                        {{ v.4 }}
                    </td>
                </tr>
                
            {% endfor %}
        </tbody>
    </table>

    {% endblock body_block %}

  
    